name: Deploy Portfolio Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Debug: Show initial directory state
      - name: Show starting state
        run: |
          echo "=== Current directory content ==="
          ls -la
          echo "=== Docs directory content ==="
          ls -la docs/
          echo "=== Images in docs/images ==="
          ls -la docs/images/
          echo "=== Source images ==="
          ls -la images/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          enable_jekyll: false
          full_commit_message: 'Deploy: ${{ github.event.head_commit.message }}'

      # Verify deployment
      - name: Verify deployment files
        run: |
          # Wait for GitHub Pages to update
          sleep 30
          
          # Create a temp directory and check the gh-pages branch
          tmp_dir=$(mktemp -d)
          cd $tmp_dir
          
          echo "=== Cloning gh-pages branch ==="
          git clone --single-branch --branch gh-pages https://github.com/michaelcolenso/metatron.git
          cd metatron
          
          echo "=== Deployed files: ==="
          ls -la
          echo "=== Deployed images: ==="
          ls -la images/
          
          # Cleanup
          cd ../..
          rm -rf $tmp_dir