name: Deploy Portfolio Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Debug - Show Structure Before
        run: |
          echo "=== WORKSPACE CONTENTS ==="
          pwd
          ls -la
          echo ""
          echo "=== DOCS DIRECTORY ==="
          ls -la docs/
          echo ""
          echo "=== IMAGES DIRECTORY ==="
          ls -la docs/images/
          echo ""
          echo "=== FILE SIZES ==="
          du -h docs/images/*

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Debug - Verify Deployment
        run: |
          echo "=== CHECKING DEPLOYMENT ==="
          DEPLOYMENT_URL="${{ steps.deployment.outputs.page_url }}"
          echo "Deployed to: $DEPLOYMENT_URL"
          echo ""
          echo "=== TESTING IMAGE ACCESS ==="
          for img in docs/images/*; do
            filename=$(basename "$img")
            url="${DEPLOYMENT_URL}images/$filename"
            echo "Testing: $url"
            curl -I "$url"
            echo ""
          done